[project]
name = "diffrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mujoco-mjx",
]

[tool.uv.sources]
mujoco-mjx = { path = "packages/mujoco/mjx" }
